Ported one test to rust and added more details to frame.rs
DeepViewML/videostream-rs pull request #3
Opened 2023-07-11 17:48 UTC by Tommy-Sand

2023-07-12 21:12 UTC, sebastient requested changes

2023-07-12 21:12 UTC, sebastient commented on src/frame.rs
> +        if ret == 0 {
In general we expect to follow the "if-error-fail" pattern where we handle errors first in the if then the non-error case continues afterwards.  To use that pattern here it would look something like.

```rust
if ret {
  let err = io::Error::last_os_error();
  return Err(Box::new(err));
}

return Ok(());
```

2023-07-12 22:15 UTC, Tommy-Sand commented on src/frame.rs
> +        if ret == 0 {
Should be fixed now

2023-08-17 22:28 UTC, sebastient approved these changes

2023-08-17 22:28 UTC, merged