added encoder.rs as well as fixed all the warning
DeepViewML/videostream-rs pull request #5
Opened 2023-08-16 22:19 UTC by saksham-auzone

2023-08-17 22:26 UTC, sebastient requested changes

2023-08-17 22:26 UTC, sebastient commented on videostream-sys/videostream.h
@saksham-auzone, this file was checked in with a conflict.  Please ensure it is the latest videostream.h (from videostream) with no further changes, then re-run updates.sh to synchronize ffi.rs.

2023-08-18 15:44 UTC, saksham-auzone commented on videostream-sys/videostream.h
The conflict should be resolved now and I have updated the ffi.rs as well

2023-08-18 16:13 UTC, sebastient approved these changes

2023-08-18 16:14 UTC, merged